theme: jekyll-theme-cayman

title: Hey Im Dulith Perera!
description: A hardworking and dedicated Computer Science undergraduate with a keen interest in AI and Machine Learning.
image: ![Profile](result.png)

