theme: jekyll-theme-cayman

title: Hey Im Dulith Perera!
description: A hardworking and dedicated Computer Science undergraduate with a keen interest in AI and Machine Learning.
<div align="center">
  <img src="Screenshot 2025-04-23 at 15.46.59.png" width="250" alt="My Photo">
</div>


